import { Ball, Calculator, Counter, CurrentAccount, FuelPump, Car } from "./types"

console.log("---------- Atividade 1 ----------")
const item1 = new Counter("Maçã")
item1.increase(2)
item1.returnValue()
item1.reset()

console.log("---------- Atividade 2 ----------")
const basketBall = new Ball("Laranja", "74,9 cm", "Synthetic leather")
basketBall.showColor()
basketBall.changeColor("Preto")
basketBall.showColor()

console.log("---------- Atividade 3 ----------")
const holder1 = new CurrentAccount(1, "Jean")
holder1.changeHolderName("Diener")
holder1.deposit(2000.3216546)
holder1.draft(0)
holder1.draft(3000)
holder1.draft(1500.45546)

console.log("---------- Atividade 4 ----------")
const calculator = new Calculator
calculator.addition(0, -4)
calculator.subtraction(2, -2)
calculator.division(25, 5)
calculator.multiplication(-10, 50)
calculator.showHistoric()

console.log("---------- Atividade 5 ----------")
const fuelPump = new FuelPump("Diesel", 6.1, 100)
fuelPump.changeFuelType("Etanol")
fuelPump.changeValuePerLiter(5.99)
fuelPump.fuelByLiter(0)
fuelPump.fuelByLiter(100)
fuelPump.fuelByValue(50)
fuelPump.addFuelToTheFuelPump(30000)
fuelPump.addFuelToTheFuelPump(20000)
fuelPump.fuelByValue(50)

console.log("---------- Atividade 6 ----------")
const onix = new Car(15)
onix.getfuelAmountInTank()
onix.fuelTheCar(20)
onix.fuelTheCar(50)
onix.drive(400)
onix.getfuelAmountInTank()
onix.fuelTheCar(50)
onix.getfuelAmountInTank()
onix.drive(100)
onix.getfuelAmountInTank()